name: Loyalty Cloudformation POC 3
on:
  workflow_dispatch:
  push:
    branches:
      - demo

  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: self-hosted
    # Necessary for Sonar to report back the the PR
    permissions:
      id-token: write
      contents: read

    environment: develop
    env: 
      build_id: test

    steps:
      - name: Get Repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        id: java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '17'
        
      - name: Current Directory
        run: |
          pwd

      - name: Install Cert
        run: |
          ls -lrt ./
          curl https://172.21.102.104/sonarqube/batch/index --cacert ./sonarqube.skechers.com.cer
          keytool -import -noprompt -trustcacerts -file ./sonarqube.skechers.com.cer -keystore ${{ steps.java.outputs.path }}/lib/security/cacerts -storepass  'changeit' || true
        env:
          MY_ENV_VAR: ${{ vars.SONAR_ROOT_CERT }}

      - id: read_from_file
        name: Read version from file
        run: | 
          version=$(cat version.txt)
          echo "version=$version" >> $GITHUB_OUTPUT

      # - name: Output version from file
      #  run: |
      #    echo "version is ${{ steps.read_from_file.outputs.version }}"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable      
        run: chmod +x ./gradlew
        
      - name: Build with Gradle
        run: ./gradlew -Plabel=${{ steps.read_from_file.outputs.version }} clean labelBuild build

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_ROOT_CERT: ${{ secrets.SONAR_ROOT_CERT }}
        run: ./gradlew build sonar -Dsonar.gradle.skipCompile=true -Dsonar.verbose=true --info
        # --stacktrace --scan --debug

      - name: Download ShiftLeft CLI
        run: |
         curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl

      - name: Validate Build Rules For PRs
        if: github.event.pull_request
        run: |
         ${GITHUB_WORKSPACE}/sl check-analysis --v2 \
           --target "tag.branch=${{ github.head_ref || github.ref }}" \
           --github-pr-number=${{ github.event.number }} \
           --github-pr-user=${{ github.repository_owner }} \
           --github-pr-repo=${{ github.event.repository.name }} \
           --github-token=${{ secrets.GITHUB_TOKEN }}
        env:
         SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}

    #Dont run this if we are in the pull request context
      - name: Validate Build Rules For Branches
        if: ${{ !github.event.pull_request }}
        run: |
         ${GITHUB_WORKSPACE}/sl check-analysis --v2 \
           --config shiftleft.yaml \
           --github-token=${{ secrets.GITHUB_TOKEN }}
        env:
         SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
